# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Luccas/ULA-8bits/project_2.cache/wt [current_project]
set_property parent.project_path C:/Luccas/ULA-8bits/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib C:/Luccas/ULA-8bits/project_2.srcs/sources_1/new/ula8bits.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top ula8bits -part xc7k70tfbv676-1


write_checkpoint -force -noxdef ula8bits.dcp

catch { report_utilization -file ula8bits_utilization_synth.rpt -pb ula8bits_utilization_synth.pb }
